account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as authView

app_name = 'account'

urlpatterns = [
    path('', authView.LoginView.as_view(
        template_name="account/login.html"), name="login"),
    path('register/', views.CreateAccountView.as_view(), name="register"),
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('logout/', authView.LogoutView.as_view(), name="logout")
]

coffee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('farmer.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('staff/', include('staff.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

farmer/urls.py
from django.urls import path
from . import views

app_name = "farmer"

urlpatterns = [
    path('', views.HomePageView.as_view(), name="index"),
    path('factories/', views.FactoryList.as_view(), name="factories"),
    path('product/', views.CreateCollectionScheduler.as_view(), name='product'),
    path('schedules/', views.ScheduleList.as_view(), name='schedules'),
    path('pending_payment/', views.PendingPayment.as_view(), name="pending_payment"),
    path('payment_history/', views.PaymentHistory.as_view(), name="payment_history")
]

staff/urls.py
from django.urls import path, include
from . import views

# super admin routes
staff_patterns = ([
    path('', views.HomeView.as_view(), name="index"),
    path('factory/add/', views.CreateFactoryView.as_view(),
         name="add_factory"),
    path('factories/', views.FactoryListView.as_view(),
         name="factories"),
    path('factories/delete/<int:id>',
         views.FactoryDeleteView.as_view(), name="factory_delete"),
    path('factories/update/<int:pk>',
         views.FactoryUpdateView.as_view(), name="factory_update"),
    path('factory_admin/add/', views.CreateFactoryAdmin.as_view(),
         name="add_station_admin"),
    path('factory_admins/', views.FactoryAdminList.as_view(),
         name="factory_admins_list"),
    path('delete_factory_admin/<int:pk>/', views.DeleteFactoryStaff.as_view(),
         name="delete_factory_admin"),
    path('edit_factory_admin/<int:pk>/',
         views.EditFactoryStaff.as_view(), name="edit_factory_admin"),
    path('profile/',
         views.ProfileView.as_view(), name="profile")
], 'staff')

# factory admin routes
factory_admin = ([
    path('product', views.NewProduct.as_view(), name="products_schedule"),
    path('product_reject/', views.RejectProduct.as_view(), name="product_reject"),
    path('product_reject_accepted/',
         views.ReRejectProduct.as_view(), name="re_product_reject"),
    path('schedule_date/<int:pk>/',
         views.AddScheduleDate.as_view(), name="schedule_product"),
    path('products_scheduled/', views.ScheduledProduct.as_view(), name="scheduled"),
    path('products_collected/', views.CollectedProduct.as_view(), name="collected"),
    path('products_collect/<int:pk>/',
         views.CollectProductView.as_view(), name="product_collect"),
    path('accountant', views.CreateFactoryStaff.as_view(), name="add_accountant"),
    path('staff_list', views.FactoryStaffList.as_view(), name="staff_list"),
    path('staff/<int:pk>/delete',
         views.DeleteStaffMember.as_view(), name="delete_staff"),

], 'factory_admin')

# factort accountant routes
factory_accountant = ([
    path('transact/<int:product>', views.MakePayDeposit.as_view(), name="transact"),
    path('payment_history', views.PaymentHistory.as_view(), name="payment_history"),
    path('pending_balances', views.PendingBalances.as_view(), name="balances")
], 'accountant')
urlpatterns = [
    path('', include(staff_patterns)),
    path('', include(factory_admin)),
    path('', include(factory_accountant))
]

farmer/models.py
from django.db import models
from account.models import UserModel
from staff.models import Factory


class NotificationMessage(models.Model):
    farmer = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    subject = models.CharField(max_length=300, verbose_name="title")
    message = models.TextField(verbose_name="body")
    sender = models.ForeignKey(
        UserModel, on_delete=models.CASCADE, related_name="message_sender")

    def __str__(self):
        return f"{self.farmer.username} Message"


class Product(models.Model):
    scheduler = [
        ('0', 'No'),
        ('1', 'Yes'),
        ('2', 'Pending')
    ]
    collected = [
        ('0', 'No'),
        ('1', 'Yes')
    ]

    farmer = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    approximate_quantity = models.IntegerField(default=0)
    factory = models.ForeignKey(Factory, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0, verbose_name="coffee")
    price_per_kg = models.IntegerField(default=0, verbose_name="price")
    date = models.DateField(auto_now_add=True)
    scheduled = models.CharField(max_length=2, choices=scheduler, default='2')
    date_scheduled = models.DateField(null=True)
    collected = models.CharField(max_length=2, choices=collected, default='0')

    def __str__(self):
        return f"{self.farmer.username} - {self.quantity}Kgs"


class Payment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    total_amount = models.IntegerField(default=0)
    paid_amount = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.product.id} {self.total_amount}"


class Transaction(models.Model):
    transaction_types = [
        ('deposit', 'Deposit'),
        ('cancel', 'Cancel'),
        ('correction', 'Correction')
    ]
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.IntegerField()
    date = models.DateField(auto_now_add=True)
    initiated_by = models.ForeignKey(
        UserModel, on_delete=models.CASCADE, related_name="accountant")
    transaction_type = models.CharField(
        max_length=20, choices=transaction_types)

    def __str__(self):
        return f"{self.user.username} - {self.amount} - {self.transaction_type}"

    def get_absolute_url(self):
        pass

farmer/forms.py
from django import forms
from .models import Product

class CreateProduceForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['factory', 'approximate_quantity']

farmer/views.py
from django.shortcuts import render, get_list_or_404, redirect, get_object_or_404, reverse
from django.views import generic, View
from staff.models import FactoryPrice, Factory
from .models import Product, Payment, Transaction
from . import forms as custForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


class HomePageView(View):
    def get(self, request):
        try:
            userlevel = self.request.user.userlevel

            if userlevel == 'accounts' or userlevel == 'factory_admin' or userlevel == 'manager':
                return redirect('staff:index')
        except:
            pass

        top_factory = FactoryPrice.objects.all()[:10]
        context = {
            "factories": top_factory
        }

        return render(request, 'farmer/home.html', context)


class FactoryList(generic.ListView):
    model = FactoryPrice
    context_object_name = 'factories'
    template_name = 'farmer/factory_list.html'


class CreateCollectionScheduler(LoginRequiredMixin, UserPassesTestMixin, View):
    login_url = "/account/"

    form = custForm.CreateProduceForm
    template_name = 'farmer/product_create_form.html'

    def test_func(self):
        return self.request.user.userlevel == "farmer"

    def get(self, request):
        return render(request, self.template_name, context={'form': self.form()})

    def post(self, request):
        form = self.form(request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.farmer = request.user
            factory = product.factory
            factory_price = get_object_or_404(
                FactoryPrice, factory_id=factory.pk)
            product.price_per_kg = factory_price.price
            product.save()
            messages.success(
                request, 'Your request was send successfully wait for processing')
            return redirect('farmer:schedules')
        return render(request, self.template_name, context={'form': form})


class ScheduleList(LoginRequiredMixin, UserPassesTestMixin, generic.ListView):
    login_url = "/account/"
    model = Product

    def test_func(self):
        return self.request.user.userlevel == "farmer"

    def get_queryset(self):
        return Product.objects.filter(farmer=self.request.user)


class PendingPayment(LoginRequiredMixin, UserPassesTestMixin, View):
    login_url = "/account/"
    template_name = 'farmer/payment_list.html'

    def test_func(self):
        return self.request.user.userlevel == "farmer"

    def get(self, request):
        pending = []
        for payment in Payment.objects.all():
            if payment.product.farmer == request.user:
                pend = payment.total_amount - payment.paid_amount
                if pend > 0:
                    payment.balance = pend
                    pending.append(payment)
        return render(request, self.template_name, context={'payments': pending})


class PaymentHistory(LoginRequiredMixin, UserPassesTestMixin, View):
    login_url = "/account/"
    context_object_name = "transactions"

    def test_func(self):
        return self.request.user.userlevel == "farmer"

    def get(self, request):
        trans = list()
        user = self.request.user
        transactions = Transaction.objects.all()
        for transaction in transactions:
            farmer = transaction.product.farmer
            if farmer.id == user.id:
                trans.append(transaction)
        return render(request, 'farmer/transaction_list.html', context={
            "transactions": trans
        })

farmer/templates/farmer/factory_list.html
{% extends 'farmer/layout.html' %}

{% block body %}
<div class="container">
    <div class="mt-4 card-deck">
        {% for factory_price in factories%}
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h4>{{ factory_price.factory.name }}</h4>
                    <hr>
                </div>
                <div class="card-text">
                    <div class="columns">
                        <p><strong>Location: </strong> {{ factory_price.factory.address }}</p>
                        <p><strong>Contact: </strong> {{ factory_price.factory.phone_number }} </p>
                        <p><strong>Email: </strong> {{ factory_price.factory.email }}</p>
                        <p><strong>Buying Price: </strong> Ksh. {{ factory_price.price }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

farmer/templates/farmer/home.html
{% extends 'farmer/layout.html' %}
{% load static %}

{% block body %}
<!--Carousel Goes Here-->
<!--End of Carousel-->
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'coffee1.jpg' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h1>Coffee is a beverage that puts one to sleep when not drank</h1>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'coffee2.jpg' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h1>I judge a restaurant by the bread and by the coffee.</h1>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="container mt-4">
    <h4>Top Price Factories</h4>
    <div class="table-response">
        <table class="table table-striped dt_table">
            <thead>
                <tr>
                    <th>Factory Name</th>
                    <th>Previous Price</th>
                    <th>Current Price</th>
                </tr>
            </thead>
            <tbody>
                {% for price in factories %}
                <tr>
                    <td>{{ price.factory.name }}</td>
                    <td>
                        {% if price.previous_price %}
                        {{'Ksh.'}} {{ price.previous_price }}
                        {% else %}
                        --
                        {% endif %}
                    </td>
                    <td>Ksh. {{ price.price }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}
{% block scripts %}
{% include 'staff/dataTables.html' %}
{% endblock %}

farmer/templates/farmer/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Coffee {% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/@fortawesome/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" rel="stylesheet" type="text/css" href="{% static 'universal/universal.css' %}">
    {% block styles %}{% endblock %}
</head>

<body>
    <nav class=" navbar navbar-dark bg-dark navbar-expand-sm fixed-top" role="navigation" aria-label="navigation bar">
        <a href="" class="navbar-brand">Coffee</a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#homeNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="homeNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'farmer:index' %}" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'farmer:factories' %}" class="nav-link">Factories</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">My Products</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'farmer:product' %}" class="dropdown-item">New</a>
                        <a href="{% url 'farmer:schedules' %}" class="dropdown-item">Schedules</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Payments Details</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'farmer:pending_payment' %}" class="dropdown-item">Pending Payments</a>
                        <a href="{% url 'farmer:payment_history' %}" class="dropdown-item">Payment History</a>
                    </div>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'account:register' %}" class="nav-link">Create Account</a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'account:login' %}" class="nav-link">Login</a>
                </li>
                {% else %}
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Settings</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'account:profile' %}" class="dropdown-item">Profile</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a href="{% url 'account:logout' %}" class="nav-link">Logout</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% if messages %}
    <div class="container mt-3">
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
            <p>{{message}}</p>
        </div>
        {% endfor %}
    </div>
    {% endif %}
    {% block body %}
    {% endblock %}

    <script src="{% static 'node_modules/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'node_modules/popper.js/dist/popper.min.js' %}"></script>
    <script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'node_modules/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'node_modules/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    {% block scripts %}{% endblock %}
</body>

</html>

farmer/templates/farmer/payment_list.html
{% extends 'farmer/layout.html' %}

{% block body %}
<div class="container mt-3">
    <h4>Top Price Factories</h4>
    <div class="table-response">
        <table class="table table-striped dt_table">
            <thead>
                <tr>
                    <th>Factory</th>
                    <th>Total Amount</th>
                    <th>Paid Amount</th>
                    <th>Balance</th>
                </tr>
            </thead>
            <tbody>
                {% for payment in payments %}
                <tr>
                    <td> {{payment.product.id}} </td>
                    <td> {{payment.total_amount}} </td>
                    <td> {{payment.paid_amount}} </td>
                    <td> {{payment.balance}} </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}
{% block scripts %}
{% include 'staff/dataTables.html' %}
{% endblock %}

farmer/templates/farmer/product_create_form.html
{% extends 'farmer/layout.html' %}

{% load crispy_forms_tags %}

{% block body %}
<div class="addForm mt-5">
    <form action="" method="POST" class="mt-3">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="form-group">
            <button class="btn btn-outline-primary">Send Request</button>
        </div>
    </form>
</div>
{% endblock %}

farmer/templates/farmer/product_list.html
{% extends 'farmer/layout.html' %}

{% block body %}
<div class="container mt-3">
    <h4>Top Price Factories</h4>
    <div class="table-response">
        <table class="table table-striped dt_table">
            <thead>
                <tr>
                    <th>Factory</th>
                    <th>Send Date</th>
                    <th>Status</th>
                    <th>Scheduled Date</th>
                </tr>
            </thead>
            <tbody>
                {% for item in object_list %}
                <tr>
                    <td>{{item.factory.name}}</td>
                    <td>{{item.date}}</td>
                    <td>
                        {% if item.scheduled == '2' %}
                        <span class="text-primary">Not Reviewed</span>
                        {% elif item.scheduled == '0' %}
                        <span class="text-danger">Not Approved</span>
                        {% elif item.scheduled == '1' %}
                        <span class="text-success">Scheduled</span>
                        {% endif %}
                    </td>
                    <td>
                        {% if item.scheduled == '1' %}
                        {{item.date_scheduled}}
                        {% else %}
                        --
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}
{% block scripts %}
{% include 'staff/dataTables.html' %}
{% endblock %}

farmer/templates/farmer/transaction_list.html
{% extends 'farmer/layout.html' %}

{% block body %}
<div class="container mt-3">
    <h4>Top Price Factories</h4>
    <div class="table-response">
        <table class="table table-striped dt_table">
            <thead>
                <tr>
                    <th>Factory</th>
                    <th>Date</th>
                    <th>Amount</th>
                    <th>Transaction Type</th>
                </tr>
            </thead>
            <tbody>
                {% for transaction in transactions %}
                <tr>
                    <td> {{transaction.product.factory.name}} </td>
                    <td> {{transaction.date}} </td>
                    <td> Ksh. {{transaction.amount}} </td>
                    <td> {{transaction.transaction_type.capitalize}} </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}
{% block scripts %}
{% include 'staff/dataTables.html' %}
{% endblock %}